# Etapa de construcción
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN apk add libc6-compat
RUN npm install -g npm@latest
RUN npm install

COPY . .

RUN npm run build

# Instalar las dependencias de la carpeta functions/ usando npm
RUN npm install --prefix functions
RUN npm run build --prefix functions

# Comando para iniciar el servidor de desarrollo, los emuladores de Firebase, y Genkit
CMD [ "sh", "-c", "firebase deploy --only auth,firestore,functions,storage" ]

# Etapa de producción
FROM denoland/deno

WORKDIR /app

# El --from=build indica que se copiarán los archivos de la etapa de construcción (FROM node:20-alpine AS build)
COPY --from=build /app/server ./server
COPY --from=build /app/dist ./dist
COPY package*.json ./

RUN deno install --allow-scripts=npm:@firebase/util@1.11.0,npm:sharp@0.33.5,npm:protobufjs@7.4.0

EXPOSE 3009

# Comando para iniciar la aplicación con Deno
CMD ["deno", "task", "serve"]